name: dev-4
spring:
  #file upload setting
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  #datesource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.254.247:3306/scd-goods?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: lq113314799LQ
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒）
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 是否自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒）
      pool-name: DateSourceHikariCP   # 连接池名称
      max-lifetime: 1800000           # 连接的生命时长（毫秒）
      connection-test-query: SELECT 1 # 连接测试sql
  #redis
  redis:
    database: 0
    # Redis服务器地址
    host: 39.98.254.247
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 30000
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      shutdown-timeout: 100ms # 关闭超时时间 默认 100ms
      pool: # lettuce 连接池
        max-active: 8 # 连接池最大连接数 默认 8（-1 ：表示没有限制）
        max-wait: 60000ms # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
        max-idle: 8 # 最大空闲连接  默认 8
        min-idle: 0 # 最小空闲连接  默认 0
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:9090
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: ALWAYS

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.scd.goods.entity.po
  global-config:
      id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      db-column-underline: false
      refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  #type-enums-package: com.youedata.foxconn.inquiry.common.enums


#Eureka Client
eureka:
  client:
    #注册进eureka注册中心 false 表示不向注册中心注册自己
    register-with-eureka: true
    #检索服务 false自己就是注册中心，不需要检索自己服务
    fetch-registry: true
  instance:
    #鼠标指上去显示IP
    prefer-ip-address: true
    #客户端向Eureka发送心跳的频率 默认30秒
    lease-expiration-duration-in-seconds: 30
    #Eureka在接收到最后一次心跳等待时间上限 默认90秒 超时将删除服务
    lease-renewal-interval-in-seconds: 90



